export const AMBUCYCLE_PLANS = [
  {
    title: "Basic Responder Plan",
    price: "20,000",
    features: [
      "First responder dispatch to site for care treatment & coordination <strong>(5 call out per year) </strong>",
      "24/7 coverage and response through the Help Station Call Center (available for support)",
      "Access to the HELP Mobile App",
      "Referral to Emergency - Ready Hospitals on HELP Platform",
      "Access to ambulance transfer service if needed. Call-out fee applies",
      "<strong>Restricted to plan owner</strong>",
    ],
    color: "primary-4",
    bgColor: "[#d9efe5]/50",
    icon: "icons/green_check_circle.svg",
  },
  {
    title: "Advanced Responder Plan",
    price: "35,000",
    features: [
      "First responder dispatch to site for care treatment & coordination  <strong>(7 call-outs per year) </strong>",
      "24/7 coverage and response through the Help Station Call Center (available for support)",
      "Access to HELP Mobile App",
      "Referral to Emergency - Ready Hospitals on HELP Platform",
      "<strong>For Plan owner & 2 family members</strong>",
    ],
    color: "primary-1",
    bgColor: "[#fee3d5]/50",
    icon: "icons/orange_check_circle.svg",
  },
  {
    title: "Family Responder Plan",
    price: "55,000",
    features: [
      "First responder dispatch to site for care treatment & coordination <strong>(10 call-outs per year)</strong>",
      "24/7 coverage and response through the Help Station Call Center (available for support)",
      "Access to HELP Mobile App",
      "Referral to Emergency - Ready Hospitals on HELP Platform",
      "<strong>For Plan owner & 3 family members</strong>",
    ],
    color: "primary-light-2",
    bgColor: "[#F7C436]/50",
    icon: "icons/golden_yellow_check_circle.svg",
  },
];
