import MainLayout from "@/components/layout/MainLayout";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="md:mt-12">
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
