import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/layout/Layout";

export const metadata: Metadata = {
  title: "Help-station",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex justify-center items-center max-w-[1400] h-full">
        <div className="w-full h-[100%] my-5">{children}</div>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
